# Use a build matrix to do two builds in parallel:
# one using CMake, and one using make.
language: cpp

# Cache Ubuntu apt packages.
cache: apt

compiler: gcc

before_install:
  - export NUM_THREADS=4
  - export SCRIPTS=./scripts/travis

install:
  - sudo -E $SCRIPTS/travis_install.sh

before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

script: $SCRIPTS/travis_build_and_test.sh

notifications:
# Emails are sent to the committer's git-configured email address by default,
# but only if they have access to the repository.  To enable Travis on your
# public fork of Caffe, just go to travis-ci.org and flip the switch on for
# your Caffe fork.  To configure your git email address, use:
#     git config --global user.email me@example.com
  email:
    on_success: always
    on_failure: always
